CREATE TABLE IF NOT EXISTS core_logs (
    log_id                          INTEGER               DEFAULT ON NULL core_log_id.NEXTVAL CONSTRAINT nn_core_logs_log_id NOT NULL,
    log_parent                      INTEGER,
    app_id                          NUMBER(8,0)           CONSTRAINT nn_core_logs_app_id NOT NULL,
    page_id                         NUMBER(8,0),
    user_id                         VARCHAR2(128),
    flag                            CHAR(1)               CONSTRAINT nn_core_logs_flag NOT NULL,
    action_name                     VARCHAR2(64),
    module_name                     VARCHAR2(64),
    module_line                     NUMBER(8,0),
    module_timer                    VARCHAR2(12),
    arguments                       VARCHAR2(4000),
    payload                         VARCHAR2(4000),
    debug_id                        INTEGER,
    session_id                      INTEGER,
    created_at                      TIMESTAMP(6)          CONSTRAINT nn_core_logs_created_at NOT NULL,
    --
    CONSTRAINT pk_core_logs
        PRIMARY KEY (log_id)
)
PARTITION BY RANGE (created_at) INTERVAL(NUMTODSINTERVAL(1, 'DAY')) (
    PARTITION P00 VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00')
);
--
COMMENT ON TABLE core_logs IS 'Various core_logs raised in application; daily partitions';
--
COMMENT ON COLUMN core_logs.log_id          IS 'Log ID generated from LOG_ID sequence';
COMMENT ON COLUMN core_logs.log_parent      IS 'Parent log record; dont use FK to avoid deadlocks';
COMMENT ON COLUMN core_logs.app_id          IS 'APEX Application ID';
COMMENT ON COLUMN core_logs.page_id         IS 'APEX Application PAGE ID';
COMMENT ON COLUMN core_logs.user_id         IS 'User ID';
COMMENT ON COLUMN core_logs.flag            IS 'Type of error listed in tree package specification; FK missing for performance reasons';
COMMENT ON COLUMN core_logs.action_name     IS 'Action name to distinguish position in module or use it as warning/error names';
COMMENT ON COLUMN core_logs.module_name     IS 'Module name (procedure or function name)';
COMMENT ON COLUMN core_logs.module_line     IS 'Line in the module';
COMMENT ON COLUMN core_logs.module_timer    IS 'Time interval indicating successful finish';
COMMENT ON COLUMN core_logs.arguments       IS 'Arguments passed to module';
COMMENT ON COLUMN core_logs.payload         IS 'Formatted call stack, error stack or query with DML error';
COMMENT ON COLUMN core_logs.debug_id        IS '';
COMMENT ON COLUMN core_logs.session_id      IS 'Session ID (generated by APEX) from sessions table';
COMMENT ON COLUMN core_logs.created_at      IS 'Timestamp of creation';

