CREATE TABLE IF NOT EXISTS core_locks (
    lock_id                         NUMBER                GENERATED BY DEFAULT AS IDENTITY START WITH 1000 CONSTRAINT core_locks_nn_lock_id NOT NULL,
    object_owner                    VARCHAR2(32)          CONSTRAINT core_locks_nn_object_owner NOT NULL,
    object_type                     VARCHAR2(32)          CONSTRAINT core_locks_nn_object_type NOT NULL,
    object_name                     VARCHAR2(128)         CONSTRAINT core_locks_nn_object_name NOT NULL,
    locked_by                       VARCHAR2(128)         CONSTRAINT core_locks_nn_locked_by NOT NULL,
    locked_at                       DATE                  CONSTRAINT core_locks_nn_locked_at NOT NULL,
    expire_at                       DATE,
    counter                         NUMBER(4,0),
    object_payload                  CLOB,
    object_hash                     VARCHAR2(64),
    audit_trail                     VARCHAR2(128),
    --
    CONSTRAINT core_locks_pk
        PRIMARY KEY (lock_id)
);
--
COMMENT ON TABLE core_locks IS 'To track DDL events for objects locks';
--
COMMENT ON COLUMN core_locks.lock_id            IS '';
COMMENT ON COLUMN core_locks.object_owner       IS '';
COMMENT ON COLUMN core_locks.object_type        IS '';
COMMENT ON COLUMN core_locks.object_name        IS '';
COMMENT ON COLUMN core_locks.locked_by          IS '';
COMMENT ON COLUMN core_locks.locked_at          IS '';
COMMENT ON COLUMN core_locks.expire_at          IS '';
COMMENT ON COLUMN core_locks.counter            IS '';
COMMENT ON COLUMN core_locks.object_payload     IS '';
COMMENT ON COLUMN core_locks.object_hash        IS '';
COMMENT ON COLUMN core_locks.audit_trail        IS '';

