CREATE TABLE IF NOT EXISTS core_locks (
    lock_id                         NUMBER                GENERATED BY DEFAULT AS IDENTITY START WITH 1000 NOT NULL,
    object_owner                    VARCHAR2(32)          NOT NULL,
    object_type                     VARCHAR2(32)          NOT NULL,
    object_name                     VARCHAR2(128)         NOT NULL,
    locked_by                       VARCHAR2(128)         NOT NULL,
    locked_at                       DATE                  NOT NULL,
    expire_at                       DATE,
    --
    CONSTRAINT core_locks_pk
        PRIMARY KEY (lock_id)
);
--
COMMENT ON TABLE core_locks IS '';
--
COMMENT ON COLUMN core_locks.lock_id        IS '';
COMMENT ON COLUMN core_locks.object_owner   IS '';
COMMENT ON COLUMN core_locks.object_type    IS '';
COMMENT ON COLUMN core_locks.object_name    IS '';
COMMENT ON COLUMN core_locks.locked_by      IS '';
COMMENT ON COLUMN core_locks.locked_at      IS '';
COMMENT ON COLUMN core_locks.expire_at      IS '';

